spring.application.name=shortener
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/url_shortener
spring.r2dbc.username=matias
spring.r2dbc.password=secret123

spring.sql.init.mode=always
spring.sql.init.platform=postgres
